#Configuracion de base de datos
server.port=8085
spring.jpa.database=POSTGRESQL
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/bbdd_curso_apis
spring.datasource.username=postgres
spring.datasource.password=123

#JPA y Hibernate

#Cuando se haga un cambio automaticamente se va a actualizar
spring.jpa.hibernate.ddl-auto=update
#Cuando se agrega un campo automaticamente se va a actualizar
spring.jpa.show-sql=true

spring.jpa.generate-ddl=true
